### ISSUE TITLE
 no [[IsHTMLDDA]] object available for testing

### ISSUE THREAD

**Issue by damorim** [damorim/jsfuzz#15]
Notice this is preventing correct execution of lots of tests. Likely configuration problem... Apparently, it is using some feature that only jsc has as jsc does not fail (for the case i have seen). 

===
shortfuzz_diff_report_fuzzed_mozilla_test262_annexB_built-ins_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_annexB_language_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_ArrayBuffer_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_ArrayIteratorPrototype_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_Array_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_AsyncFunction_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_Atomics_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_BigInt_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_Boolean_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_DataView_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_Date_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_decodeURIComponent_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_decodeURI_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_encodeURIComponent_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_encodeURI_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_Error_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_eval_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_Function_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_GeneratorFunction_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_GeneratorPrototype_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_global_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_Infinity_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_isFinite_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_isNaN_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_IteratorPrototype_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_JSON_.txt:Error: no [[IsHTMLDDA]] object available for testing
shortfuzz_diff_report_fuzzed_mozilla_test262_built-ins_Map_.txt:Error: no [[IsHTMLDDA]] object available for testing

**Comment by damorim** [comment]
@MateusAraujoBorges, vc. tem condicoes de assumir esta issue?

**Comment by MateusAraujoBorges** [comment]
Não nos próximos dias. Tenho algum tempo disponível hoje para dar uma olhada rápida, mas não deve ser suficiente
